import os
import datetime
from core import db

def generate_html_report(project_id, output_path):
    conn = db.get_connection()
    cur = conn.cursor()
    
    # Project Info
    cur.execute("SELECT name, created_at FROM projects WHERE id=?", (project_id,))
    p_row = cur.fetchone()
    if not p_row:
        return False, "Project not found"
    project_name, created_at = p_row

    # Hosts
    cur.execute("SELECT id, ip_address, hostname, os_info, status FROM hosts WHERE project_id=?", (project_id,))
    hosts = cur.fetchall()
    
    # Services
    cur.execute("""
        SELECT h.ip_address, s.port, s.protocol, s.service_name, s.product, s.version, s.state
        FROM services s
        JOIN hosts h ON s.host_id = h.id
        WHERE h.project_id=?
        ORDER BY h.ip_address, s.port
    """, (project_id,))
    services = cur.fetchall()
    
    conn.close()
    
    # Build HTML
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Redboar Report: {project_name}</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 20px; background: #f4f4f4; }}
            .container {{ max-width: 900px; margin: 0 auto; background: white; padding: 40px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
            h1 {{ color: #d32f2f; border-bottom: 2px solid #d32f2f; padding-bottom: 10px; }}
            h2 {{ color: #333; margin-top: 30px; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
            th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
            th {{ background-color: #f8f9fa; color: #555; }}
            tr:hover {{ background-color: #f1f1f1; }}
            .badge {{ padding: 4px 8px; border-radius: 4px; font-size: 0.85em; color: white; }}
            .up {{ background-color: #28a745; }}
            .down {{ background-color: #dc3545; }}
            .open {{ background-color: #007bff; }}
            .meta {{ color: #777; font-size: 0.9em; margin-bottom: 30px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Redboar Penetration Test Report</h1>
            <div class="meta">
                <strong>Project:</strong> {project_name}<br>
                <strong>Date:</strong> {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}<br>
                <strong>Generated by:</strong> Redboar Framework
            </div>

            <h2>Executive Summary</h2>
            <p>This report contains the technical findings of the automated assessment performed on the target infrastructure.</p>
            <ul>
                <li>Total Hosts Found: {len(hosts)}</li>
                <li>Total Services Discovered: {len(services)}</li>
            </ul>

            <h2>Target Hosts</h2>
            <table>
                <thead>
                    <tr>
                        <th>IP Address</th>
                        <th>Hostname</th>
                        <th>OS</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
    """
    
    for h in hosts:
        status_class = "up" if h['status'] == 'up' else "down"
        html += f"""
                    <tr>
                        <td>{h['ip_address']}</td>
                        <td>{h['hostname'] or 'N/A'}</td>
                        <td>{h['os_info'] or 'Unknown'}</td>
                        <td><span class="badge {status_class}">{h['status'].upper()}</span></td>
                    </tr>
        """

    html += """
                </tbody>
            </table>

            <h2>Service Discovery</h2>
            <table>
                <thead>
                    <tr>
                        <th>Host</th>
                        <th>Port</th>
                        <th>Service</th>
                        <th>Product/Version</th>
                        <th>State</th>
                    </tr>
                </thead>
                <tbody>
    """
    
    for s in services:
        html += f"""
                    <tr>
                        <td>{s['ip_address']}</td>
                        <td>{s['port']}/{s['protocol']}</td>
                        <td>{s['service_name']}</td>
                        <td>{s['product']} {s['version']}</td>
                        <td><span class="badge open">{s['state']}</span></td>
                    </tr>
        """
        
    html += """
                </tbody>
            </table>
            
            <p style="margin-top:50px; text-align:center; color:#aaa; font-size:0.8em;">Generated by Redboar</p>
        </div>
    </body>
    </html>
    """
    
    try:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
        return True, output_path
    except Exception as e:
        return False, str(e)
